name: Setup
description: Checkout, setup Bun, cache dependencies, and install

inputs:
  turbo-cache-key:
    description: Unique key suffix for Turbo cache
    required: true

runs:
  using: composite
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Cache Bun dependencies
      uses: actions/cache@v4
      with:
        path: ~/.bun/install/cache
        key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
        restore-keys: |
          ${{ runner.os }}-bun-

    - name: Cache Turbo
      uses: actions/cache@v4
      with:
        path: .turbo
        key: ${{ runner.os }}-turbo-${{ inputs.turbo-cache-key }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-turbo-${{ inputs.turbo-cache-key }}-

    - name: Install dependencies
      shell: bash
      run: bun install --frozen-lockfile
